package so.drafft.core.ui.theme

import androidx.compose.foundation.layout.size
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.automirrored.outlined.*
import androidx.compose.material.icons.automirrored.rounded.*
import androidx.compose.material.icons.outlined.*
import androidx.compose.material.icons.rounded.*
import androidx.compose.material3.Icon
import androidx.compose.runtime.Composable
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.unit.Dp
import androidx.compose.ui.unit.dp

/**
 * The iPhone app names its glyphs with SF Symbols; data and screens keep those names (sports,
 * prompt categories, icebreaker kinds...) and this is the one place that draws them on Android,
 * with Material Symbols (rounded for filled symbols, outlined for outline ones). One icon per
 * meaning: never map two different items of a list to the same glyph.
 */
object Symbols {
    private val table: Map<String, ImageVector> by lazy {
        mapOf(
            "alarm.fill" to Icons.Rounded.Alarm,
            "arrow.clockwise" to Icons.Rounded.Refresh,
            "arrow.counterclockwise" to Icons.Rounded.Replay,
            "arrow.down.circle.fill" to Icons.Rounded.ArrowCircleDown,
            "arrow.left.arrow.right" to Icons.Rounded.SwapHoriz,
            "arrow.triangle.2.circlepath" to Icons.Rounded.Autorenew,
            "arrow.up" to Icons.Rounded.ArrowUpward,
            "arrow.up.right" to Icons.Rounded.NorthEast,
            "arrow.uturn.backward" to Icons.AutoMirrored.Rounded.Undo,
            "arrowshape.turn.up.left" to Icons.AutoMirrored.Outlined.Reply,
            "arrowshape.turn.up.left.fill" to Icons.AutoMirrored.Rounded.Reply,
            "beach.umbrella" to Icons.Rounded.BeachAccess,
            "bell" to Icons.Outlined.Notifications,
            "bell.badge.fill" to Icons.Rounded.NotificationImportant,
            "bell.fill" to Icons.Rounded.Notifications,
            "bell.slash" to Icons.Outlined.NotificationsOff,
            "bell.slash.fill" to Icons.Rounded.NotificationsOff,
            "bicycle" to Icons.Rounded.PedalBike,
            "bolt.fill" to Icons.Rounded.Bolt,
            "bubble.left" to Icons.Outlined.ChatBubbleOutline,
            "bubble.left.and.bubble.right" to Icons.Outlined.Forum,
            "bubble.left.and.bubble.right.fill" to Icons.Rounded.Forum,
            "bubble.left.fill" to Icons.Rounded.ChatBubble,
            "calendar" to Icons.Outlined.CalendarMonth,
            "calendar.badge.checkmark" to Icons.Rounded.EventAvailable,
            "calendar.badge.exclamationmark" to Icons.Rounded.EventBusy,
            "calendar.badge.minus" to Icons.Rounded.EventBusy,
            "calendar.badge.plus" to Icons.Rounded.EditCalendar,
            "camera" to Icons.Outlined.PhotoCamera,
            "camera.fill" to Icons.Rounded.PhotoCamera,
            "checkmark" to Icons.Rounded.Check,
            "checkmark.circle.fill" to Icons.Rounded.CheckCircle,
            "checkmark.seal.fill" to Icons.Rounded.Verified,
            "checkmark.shield.fill" to Icons.Rounded.VerifiedUser,
            "chevron.down" to Icons.Rounded.KeyboardArrowDown,
            "chevron.left" to Icons.Rounded.ChevronLeft,
            "chevron.right" to Icons.Rounded.ChevronRight,
            "chevron.up" to Icons.Rounded.KeyboardArrowUp,
            "chevron.up.chevron.down" to Icons.Rounded.UnfoldMore,
            "circle.dotted.circle" to Icons.Rounded.TrackChanges,
            "circle.grid.cross.fill" to Icons.Rounded.Workspaces,
            "clock.fill" to Icons.Rounded.Schedule,
            "doc.fill" to Icons.AutoMirrored.Rounded.InsertDriveFile,
            "doc.on.doc" to Icons.Outlined.ContentCopy,
            "doc.richtext.fill" to Icons.AutoMirrored.Rounded.Article,
            "doc.text.fill" to Icons.Rounded.Description,
            "door.left.hand.open" to Icons.AutoMirrored.Outlined.Logout,
            "ellipsis" to Icons.Rounded.MoreHoriz,
            "envelope.badge" to Icons.Outlined.MarkEmailUnread,
            "envelope.fill" to Icons.Rounded.Email,
            "envelope.open" to Icons.Outlined.Drafts,
            "envelope.open.fill" to Icons.Rounded.Drafts,
            "exclamationmark" to Icons.Rounded.PriorityHigh,
            "exclamationmark.circle.fill" to Icons.Rounded.Error,
            "exclamationmark.triangle" to Icons.Outlined.WarningAmber,
            "eye" to Icons.Outlined.Visibility,
            "eye.fill" to Icons.Rounded.Visibility,
            "eye.slash" to Icons.Outlined.VisibilityOff,
            "eye.slash.fill" to Icons.Rounded.VisibilityOff,
            "face.smiling.inverse" to Icons.Rounded.EmojiEmotions,
            "faceid" to Icons.Rounded.Face,
            "figure.archery" to Icons.Rounded.GpsFixed,
            "figure.badminton" to Icons.Rounded.SportsTennis,
            "figure.barre" to Icons.Rounded.AccessibilityNew,
            "figure.basketball" to Icons.Rounded.SportsBasketball,
            "figure.boxing" to Icons.Rounded.SportsMma,
            "figure.climbing" to Icons.Rounded.Terrain,
            "figure.cross.training" to Icons.Rounded.FitnessCenter,
            "figure.dance" to Icons.Rounded.Nightlife,
            "figure.disc.sports" to Icons.Rounded.Album,
            "figure.equestrian.sports" to Icons.Rounded.BedroomBaby,
            "figure.fencing" to Icons.Rounded.SportsKabaddi,
            "figure.flexibility" to Icons.Rounded.Accessibility,
            "figure.golf" to Icons.Rounded.GolfCourse,
            "figure.gymnastics" to Icons.Rounded.SportsGymnastics,
            "figure.handball" to Icons.Rounded.SportsHandball,
            "figure.highintensity.intervaltraining" to Icons.Rounded.Timer,
            "figure.hiking" to Icons.Rounded.Hiking,
            "figure.hockey" to Icons.Rounded.SportsHockey,
            "figure.indoor.cycle" to Icons.AutoMirrored.Rounded.DirectionsBike,
            "figure.jumprope" to Icons.Rounded.Cable,
            "figure.kickboxing" to Icons.Rounded.SportsMartialArts,
            "figure.martial.arts" to Icons.Rounded.SportsKabaddi,
            "figure.mind.and.body" to Icons.Rounded.SelfImprovement,
            "figure.open.water.swim" to Icons.Rounded.Waves,
            "figure.outdoor.cycle" to Icons.AutoMirrored.Rounded.DirectionsBike,
            "figure.pickleball" to Icons.Rounded.SportsBaseball,
            "figure.pilates" to Icons.Rounded.AccessibilityNew,
            "figure.pool.swim" to Icons.Rounded.Pool,
            "figure.racquetball" to Icons.Rounded.SportsTennis,
            "figure.rower" to Icons.Rounded.Rowing,
            "figure.rugby" to Icons.Rounded.SportsRugby,
            "figure.run" to Icons.AutoMirrored.Rounded.DirectionsRun,
            "figure.skateboarding" to Icons.Rounded.Skateboarding,
            "figure.skating" to Icons.Rounded.IceSkating,
            "figure.skiing.crosscountry" to Icons.Rounded.NordicWalking,
            "figure.skiing.downhill" to Icons.Rounded.DownhillSkiing,
            "figure.snowboarding" to Icons.Rounded.Snowboarding,
            "figure.squash" to Icons.Rounded.SportsTennis,
            "figure.stair.stepper" to Icons.Rounded.Stairs,
            "figure.stairs" to Icons.Rounded.Stairs,
            "figure.strengthtraining.functional" to Icons.Rounded.FitnessCenter,
            "figure.strengthtraining.traditional" to Icons.Rounded.FitnessCenter,
            "figure.surfing" to Icons.Rounded.Surfing,
            "figure.table.tennis" to Icons.Rounded.SportsTennis,
            "figure.taichi" to Icons.Rounded.SelfImprovement,
            "figure.tennis" to Icons.Rounded.SportsTennis,
            "figure.volleyball" to Icons.Rounded.SportsVolleyball,
            "figure.walk" to Icons.AutoMirrored.Rounded.DirectionsWalk,
            "figure.water.fitness" to Icons.Rounded.Kayaking,
            "figure.wrestling" to Icons.Rounded.SportsKabaddi,
            "figure.yoga" to Icons.Rounded.SelfImprovement,
            "flag.2.crossed" to Icons.Outlined.SportsScore,
            "flag.2.crossed.fill" to Icons.Rounded.SportsScore,
            "flag.checkered" to Icons.Rounded.SportsScore,
            "flag.fill" to Icons.Rounded.Flag,
            "flame" to Icons.Outlined.LocalFireDepartment,
            "flame.fill" to Icons.Rounded.LocalFireDepartment,
            "fork.knife" to Icons.Rounded.Restaurant,
            "gearshape.fill" to Icons.Rounded.Settings,
            "globe" to Icons.Rounded.Language,
            "hand.raised.fill" to Icons.Rounded.PanTool,
            "hand.raised.slash.fill" to Icons.Rounded.DoNotTouch,
            "hand.tap.fill" to Icons.Rounded.TouchApp,
            "hand.thumbsdown.fill" to Icons.Rounded.ThumbDown,
            "hand.thumbsup.fill" to Icons.Rounded.ThumbUp,
            "heart" to Icons.Outlined.FavoriteBorder,
            "heart.circle.fill" to Icons.Rounded.Favorite,
            "heart.fill" to Icons.Rounded.Favorite,
            "heart.slash" to Icons.Outlined.HeartBroken,
            "heart.text.square" to Icons.Outlined.Feedback,
            "heart.text.square.fill" to Icons.Rounded.Feedback,
            "hourglass" to Icons.Rounded.HourglassTop,
            "infinity" to Icons.Rounded.AllInclusive,
            "info.circle.fill" to Icons.Rounded.Info,
            "key.fill" to Icons.Rounded.Key,
            "leaf.fill" to Icons.Rounded.Eco,
            "location.fill" to Icons.Rounded.NearMe,
            "location.slash.fill" to Icons.Rounded.LocationOff,
            "lock.fill" to Icons.Rounded.Lock,
            "lock.open.fill" to Icons.Rounded.LockOpen,
            "magnifyingglass" to Icons.Rounded.Search,
            "map.fill" to Icons.Rounded.Map,
            "medal" to Icons.Rounded.MilitaryTech,
            "mic.fill" to Icons.Rounded.Mic,
            "minus" to Icons.Rounded.Remove,
            "moon.fill" to Icons.Rounded.DarkMode,
            "mountain.2" to Icons.Outlined.Landscape,
            "mountain.2.fill" to Icons.Rounded.Landscape,
            "nosign" to Icons.Rounded.Block,
            "oar.2.crossed" to Icons.Rounded.Kayaking,
            "onboarding.progress.v2" to Icons.Rounded.Timeline,
            "paperplane.fill" to Icons.AutoMirrored.Rounded.Send,
            "pause.fill" to Icons.Rounded.Pause,
            "pencil" to Icons.Rounded.Edit,
            "person.2.fill" to Icons.Rounded.People,
            "person.3.fill" to Icons.Rounded.Groups,
            "person.crop.circle.fill" to Icons.Rounded.AccountCircle,
            "person.crop.circle" to Icons.Outlined.AccountCircle,
            "person.crop.circle.badge.exclamationmark" to Icons.Rounded.ManageAccounts,
            "person.crop.circle.badge.xmark" to Icons.Rounded.PersonOff,
            "person.crop.square.fill" to Icons.Rounded.AccountBox,
            "person.fill" to Icons.Rounded.Person,
            "person.text.rectangle" to Icons.Outlined.Badge,
            "phone.fill" to Icons.Rounded.Phone,
            "photo" to Icons.Outlined.Image,
            "photo.on.rectangle" to Icons.Outlined.PhotoLibrary,
            "photo.on.rectangle.angled" to Icons.Rounded.PhotoLibrary,
            "play.fill" to Icons.Rounded.PlayArrow,
            "plus" to Icons.Rounded.Add,
            "questionmark.bubble.fill" to Icons.AutoMirrored.Rounded.LiveHelp,
            "questionmark.circle.fill" to Icons.AutoMirrored.Rounded.Help,
            "quote.bubble" to Icons.Outlined.FormatQuote,
            "quote.bubble.fill" to Icons.Rounded.FormatQuote,
            "rectangle.portrait.and.arrow.right" to Icons.AutoMirrored.Rounded.Logout,
            "road.lanes" to Icons.Rounded.AddRoad,
            "sailboat.fill" to Icons.Rounded.Sailing,
            "shield.lefthalf.filled" to Icons.Rounded.Shield,
            "slider.horizontal.3" to Icons.Rounded.Tune,
            "snowflake" to Icons.Rounded.AcUnit,
            "sparkles" to Icons.Rounded.AutoAwesome,
            "square.and.arrow.down.fill" to Icons.Rounded.Download,
            "square.and.arrow.up" to Icons.Outlined.IosShare,
            "square.grid.2x2.fill" to Icons.Rounded.GridView,
            "star.fill" to Icons.Rounded.Star,
            "stop.fill" to Icons.Rounded.Stop,
            "stopwatch.fill" to Icons.Rounded.Timer,
            "sun.max" to Icons.Outlined.WbSunny,
            "sun.max.fill" to Icons.Rounded.WbSunny,
            "sunrise.fill" to Icons.Rounded.WbTwilight,
            "text.bubble.fill" to Icons.AutoMirrored.Rounded.Chat,
            "text.quote" to Icons.Rounded.FormatQuote,
            "theatermasks.fill" to Icons.Rounded.TheaterComedy,
            "thermometer.sun.fill" to Icons.Rounded.Thermostat,
            "trash" to Icons.Outlined.Delete,
            "trash.fill" to Icons.Rounded.Delete,
            "video.fill" to Icons.Rounded.Videocam,
            "water.waves" to Icons.Rounded.Water,
            "waveform" to Icons.Rounded.GraphicEq,
            "wind" to Icons.Rounded.Air,
            "wineglass.fill" to Icons.Rounded.WineBar,
            "xmark" to Icons.Rounded.Close,
            "xmark.circle.fill" to Icons.Rounded.Cancel,
            "eyes" to Icons.Rounded.RemoveRedEye,
        )
    }

    /** The glyph for an SF Symbol name; a ".fill" variant falls back to its outline and back. */
    fun vector(name: String): ImageVector =
        table[name] ?: table["$name.fill"] ?: table[name.removeSuffix(".fill")] ?: Icons.Rounded.Circle
}

/** An SF Symbol name drawn as its Material glyph ([Symbols]). Decorative unless [contentDescription] is set. */
@Composable
fun DrafftIcon(
    name: String,
    modifier: Modifier = Modifier,
    size: Dp = 20.dp,
    tint: Color = DS.palette.ink,
    contentDescription: String? = null,
) {
    Icon(Symbols.vector(name), contentDescription, modifier.size(size), tint = tint)
}
