package so.drafft.core.ui.theme

import androidx.annotation.DrawableRes
import androidx.compose.foundation.layout.size
import androidx.compose.material3.Icon
import androidx.compose.runtime.Composable
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.res.vectorResource
import androidx.compose.ui.unit.Dp
import androidx.compose.ui.unit.dp
import so.drafft.core.ui.R

/**
 * The app's icons, named as on the iPhone app (Resources/Assets.xcassets/Icons): the Solar linear
 * set, its bold twin ("<name>-bold") for the current tab, Material Symbols Light for the sports
 * Solar lacks, and a few drawn in the Solar style. The drawables in res/drawable/ic_*.xml are
 * generated from the same outlines. One icon per meaning: never map two different items of a list
 * to the same glyph.
 */
object Symbols {
    private val table: Map<String, Int> = mapOf(
            "accessibility" to R.drawable.ic_accessibility,
            "accessibility-new" to R.drawable.ic_accessibility_new,
            "add" to R.drawable.ic_add,
            "alarm" to R.drawable.ic_alarm,
            "alt-arrow-down" to R.drawable.ic_alt_arrow_down,
            "alt-arrow-left" to R.drawable.ic_alt_arrow_left,
            "alt-arrow-right" to R.drawable.ic_alt_arrow_right,
            "alt-arrow-up" to R.drawable.ic_alt_arrow_up,
            "arrow-right-up" to R.drawable.ic_arrow_right_up,
            "arrow-up" to R.drawable.ic_arrow_up,
            "badminton" to R.drawable.ic_badminton,
            "basketball" to R.drawable.ic_basketball,
            "bell" to R.drawable.ic_bell,
            "bell-off" to R.drawable.ic_bell_off,
            "bell-ring" to R.drawable.ic_bell_ring,
            "bicycling" to R.drawable.ic_bicycling,
            "body-shape" to R.drawable.ic_body_shape,
            "bolt" to R.drawable.ic_bolt,
            "boulder" to R.drawable.ic_boulder,
            "calendar" to R.drawable.ic_calendar,
            "calendar-add" to R.drawable.ic_calendar_add,
            "calendar-check" to R.drawable.ic_calendar_check,
            "calendar-minus" to R.drawable.ic_calendar_minus,
            "calendar-warning" to R.drawable.ic_calendar_warning,
            "camera" to R.drawable.ic_camera,
            "carabiner" to R.drawable.ic_carabiner,
            "chat-round" to R.drawable.ic_chat_round,
            "chat-round-line" to R.drawable.ic_chat_round_line,
            "chat-round-question-mark" to R.drawable.ic_chat_round_question_mark,
            "chat-round-quote" to R.drawable.ic_chat_round_quote,
            "chat-square-line" to R.drawable.ic_chat_square_line,
            "check" to R.drawable.ic_check,
            "check-circle" to R.drawable.ic_check_circle,
            "chef-hat" to R.drawable.ic_chef_hat,
            "chevrons-up-down" to R.drawable.ic_chevrons_up_down,
            "clock-circle" to R.drawable.ic_clock_circle,
            "close" to R.drawable.ic_close,
            "close-circle" to R.drawable.ic_close_circle,
            "copy" to R.drawable.ic_copy,
            "danger-circle" to R.drawable.ic_danger_circle,
            "danger-triangle" to R.drawable.ic_danger_triangle,
            "dialog-2" to R.drawable.ic_dialog_2,
            "dialog-2-bold" to R.drawable.ic_dialog_2_bold,
            "directions-bike" to R.drawable.ic_directions_bike,
            "diskette" to R.drawable.ic_diskette,
            "dislike" to R.drawable.ic_dislike,
            "document-text" to R.drawable.ic_document_text,
            "downhill-skiing-outline" to R.drawable.ic_downhill_skiing_outline,
            "download-minimalistic" to R.drawable.ic_download_minimalistic,
            "dumbbell-large" to R.drawable.ic_dumbbell_large,
            "exclamation-mark" to R.drawable.ic_exclamation_mark,
            "exit" to R.drawable.ic_exit,
            "eye" to R.drawable.ic_eye,
            "eye-closed" to R.drawable.ic_eye_closed,
            "face-scan-circle" to R.drawable.ic_face_scan_circle,
            "face-scan-square" to R.drawable.ic_face_scan_square,
            "fence" to R.drawable.ic_fence,
            "fencing" to R.drawable.ic_fencing,
            "file" to R.drawable.ic_file,
            "file-text" to R.drawable.ic_file_text,
            "fire" to R.drawable.ic_fire,
            "fire-bold" to R.drawable.ic_fire_bold,
            "fitness-center" to R.drawable.ic_fitness_center,
            "flag" to R.drawable.ic_flag,
            "flag-2" to R.drawable.ic_flag_2,
            "football" to R.drawable.ic_football,
            "forbidden-circle" to R.drawable.ic_forbidden_circle,
            "frisbee" to R.drawable.ic_frisbee,
            "gallery" to R.drawable.ic_gallery,
            "gallery-wide" to R.drawable.ic_gallery_wide,
            "global" to R.drawable.ic_global,
            "golf" to R.drawable.ic_golf,
            "heart" to R.drawable.ic_heart,
            "heart-bold" to R.drawable.ic_heart_bold,
            "heart-crack" to R.drawable.ic_heart_crack,
            "heart-pulse" to R.drawable.ic_heart_pulse,
            "hiking" to R.drawable.ic_hiking,
            "horseshoe" to R.drawable.ic_horseshoe,
            "hourglass" to R.drawable.ic_hourglass,
            "ice-skating-outline" to R.drawable.ic_ice_skating_outline,
            "incognito" to R.drawable.ic_incognito,
            "infinite" to R.drawable.ic_infinite,
            "info-circle" to R.drawable.ic_info_circle,
            "jump-rope" to R.drawable.ic_jump_rope,
            "kayaking" to R.drawable.ic_kayaking,
            "key" to R.drawable.ic_key,
            "kitesurfing-outline" to R.drawable.ic_kitesurfing_outline,
            "landscape-2-outline" to R.drawable.ic_landscape_2_outline,
            "leaf" to R.drawable.ic_leaf,
            "letter" to R.drawable.ic_letter,
            "letter-opened" to R.drawable.ic_letter_opened,
            "letter-unread" to R.drawable.ic_letter_unread,
            "like" to R.drawable.ic_like,
            "link-circle" to R.drawable.ic_link_circle,
            "lock-keyhole-minimalistic" to R.drawable.ic_lock_keyhole_minimalistic,
            "lock-keyhole-minimalistic-unlocked" to R.drawable.ic_lock_keyhole_minimalistic_unlocked,
            "logout-2" to R.drawable.ic_logout_2,
            "magnifier" to R.drawable.ic_magnifier,
            "map" to R.drawable.ic_map,
            "map-point" to R.drawable.ic_map_point,
            "map-point-remove" to R.drawable.ic_map_point_remove,
            "martial-arts" to R.drawable.ic_martial_arts,
            "mask-happy" to R.drawable.ic_mask_happy,
            "masks" to R.drawable.ic_masks,
            "medal-ribbons-star" to R.drawable.ic_medal_ribbons_star,
            "meditation" to R.drawable.ic_meditation,
            "menu-dots-vertical" to R.drawable.ic_menu_dots_vertical,
            "microphone" to R.drawable.ic_microphone,
            "minus" to R.drawable.ic_minus,
            "moon" to R.drawable.ic_moon,
            "music-notes" to R.drawable.ic_music_notes,
            "nordic-walking" to R.drawable.ic_nordic_walking,
            "padel" to R.drawable.ic_padel,
            "pause" to R.drawable.ic_pause,
            "pedal-bike-outline" to R.drawable.ic_pedal_bike_outline,
            "pen" to R.drawable.ic_pen,
            "phone" to R.drawable.ic_phone,
            "physical-therapy" to R.drawable.ic_physical_therapy,
            "pickleball" to R.drawable.ic_pickleball,
            "plain" to R.drawable.ic_plain,
            "play" to R.drawable.ic_play,
            "question-circle" to R.drawable.ic_question_circle,
            "quote-circle" to R.drawable.ic_quote_circle,
            "radial-blur" to R.drawable.ic_radial_blur,
            "refresh" to R.drawable.ic_refresh,
            "reply" to R.drawable.ic_reply,
            "restart" to R.drawable.ic_restart,
            "routing" to R.drawable.ic_routing,
            "rowing" to R.drawable.ic_rowing,
            "rugby" to R.drawable.ic_rugby,
            "running" to R.drawable.ic_running,
            "sailing-outline" to R.drawable.ic_sailing_outline,
            "settings" to R.drawable.ic_settings,
            "shield-check" to R.drawable.ic_shield_check,
            "shield-warning" to R.drawable.ic_shield_warning,
            "skateboarding" to R.drawable.ic_skateboarding,
            "smile-circle" to R.drawable.ic_smile_circle,
            "snowboarding" to R.drawable.ic_snowboarding,
            "snowflake" to R.drawable.ic_snowflake,
            "soundwave" to R.drawable.ic_soundwave,
            "spikeball" to R.drawable.ic_spikeball,
            "sports-gymnastics" to R.drawable.ic_sports_gymnastics,
            "sports-handball" to R.drawable.ic_sports_handball,
            "sports-hockey" to R.drawable.ic_sports_hockey,
            "sports-kabaddi" to R.drawable.ic_sports_kabaddi,
            "sports-martial-arts" to R.drawable.ic_sports_martial_arts,
            "sports-mma-outline" to R.drawable.ic_sports_mma_outline,
            "sports-tennis-outline" to R.drawable.ic_sports_tennis_outline,
            "sprint" to R.drawable.ic_sprint,
            "stairs-2" to R.drawable.ic_stairs_2,
            "star" to R.drawable.ic_star,
            "stars" to R.drawable.ic_stars,
            "steps-outline" to R.drawable.ic_steps_outline,
            "stop" to R.drawable.ic_stop,
            "stopwatch" to R.drawable.ic_stopwatch,
            "stopwatch-play" to R.drawable.ic_stopwatch_play,
            "stopwatch-play-bold" to R.drawable.ic_stopwatch_play_bold,
            "stretching" to R.drawable.ic_stretching,
            "sun" to R.drawable.ic_sun,
            "sunrise" to R.drawable.ic_sunrise,
            "surfing" to R.drawable.ic_surfing,
            "swimming" to R.drawable.ic_swimming,
            "table-tennis" to R.drawable.ic_table_tennis,
            "taichi" to R.drawable.ic_taichi,
            "target" to R.drawable.ic_target,
            "temperature" to R.drawable.ic_temperature,
            "tennis" to R.drawable.ic_tennis,
            "transfer-horizontal" to R.drawable.ic_transfer_horizontal,
            "trash-bin-minimalistic" to R.drawable.ic_trash_bin_minimalistic,
            "tuning-2" to R.drawable.ic_tuning_2,
            "umbrella" to R.drawable.ic_umbrella,
            "undo-left" to R.drawable.ic_undo_left,
            "upload-minimalistic" to R.drawable.ic_upload_minimalistic,
            "user-block" to R.drawable.ic_user_block,
            "user-check" to R.drawable.ic_user_check,
            "user-circle" to R.drawable.ic_user_circle,
            "user-circle-bold" to R.drawable.ic_user_circle_bold,
            "user-cross-rounded" to R.drawable.ic_user_cross_rounded,
            "user-heart" to R.drawable.ic_user_heart,
            "user-id" to R.drawable.ic_user_id,
            "user-rounded" to R.drawable.ic_user_rounded,
            "user-warning" to R.drawable.ic_user_warning,
            "users-group-rounded" to R.drawable.ic_users_group_rounded,
            "users-group-two-rounded" to R.drawable.ic_users_group_two_rounded,
            "verified-check" to R.drawable.ic_verified_check,
            "videocamera" to R.drawable.ic_videocamera,
            "volleyball" to R.drawable.ic_volleyball,
            "walking" to R.drawable.ic_walking,
            "water" to R.drawable.ic_water,
            "water-sun" to R.drawable.ic_water_sun,
            "weight-outline" to R.drawable.ic_weight_outline,
            "widget" to R.drawable.ic_widget,
            "wind" to R.drawable.ic_wind,
            "wineglass" to R.drawable.ic_wineglass,
    )

    @DrawableRes
    fun resource(name: String): Int = table[name] ?: error("Unknown icon: $name")

    @Composable
    fun vector(name: String): ImageVector = ImageVector.vectorResource(resource(name))
}

/** An icon from [Symbols]. Decorative unless [contentDescription] is set. */
@Composable
fun DrafftIcon(
    name: String,
    modifier: Modifier = Modifier,
    size: Dp = 20.dp,
    tint: Color = DS.palette.ink,
    contentDescription: String? = null,
) {
    Icon(Symbols.vector(name), contentDescription, modifier.size(size), tint = tint)
}
